[project]
name = "pretty-table"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "prettytable>=3.13.0",
]

[dependency-groups]
dev = [
    "ipython>=9.9.0",
    "ruff>=0.14.11",
]
