[project]
name = "backup-dir"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fabric>=3.2.2",
    "invoke>=2.2.0",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
    "pytest>=9.0.2",
    "ruff>=0.12.10",
]
