[project]
name = "heap-sandbox"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pysnooper>=1.2.3",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "uv>=0.9.21",
]
