[project]
name = "dynamic-enum"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.1",
]

[dependency-groups]
dev = [
    "ipython>=9.10.0",
    "ruff>=0.14.10",
    "ty>=0.0.16",
]
